### ISSUE TITLE
Use of unresolved identifier 'LocationConfiguration'

### ISSUE THREAD

**Issue by aphex3k** [lemberg/ios-permissions-service#11]
1. I installed the permissions service via cocoapods
1. I imported the PermissionConfiguration.xcconfig
1. I edited the config file for location permission only

I added this code to my ViewController that implements Permissible protocol:

```
        let config = LocationConfiguration(.always)
        
        Permission<LocationPermission>.prepare(for: self, with: config) { (granted) in
            if granted {
                print("Granted")
            } else {
                print("Error")
            }
            
        }

```

LocationConfiguration is undefined when compiling...
LocationPermission is undefined when compiling...

**Comment by hellensoloviy** [comment]
Hi, aphex3k!

**1.** Why are you importing and editing the **.xcconfig** file if you are installing via **cocoapods**? 
You need to config and import this file only in case of **Carthage**. If u want to use **cocoapods** u don't need to do any additional config, but only simple default install with: 

`  pod "PermissionsService/Location"` 

in your **.pod** file. 
_Please see the link: https://github.com/lemberg/ios-permissions-service#cocoapods_

**2.** And about **undefined compiling issue**. 
Is the Permissible protocol undefined too? Have u add `import PermissionsService` to this ViewController?
